name: "Discord Update Class Names"
author: "fedeericodl"
description: "Automated CSS class name synchronization tool for Discord theme developers"
inputs:
    files:
        description: |
            Files/directories to process (comma/newline separated)
            Example: |
                src/theme/**/*.scss
                theme.css
                components/*.scss
        required: true
    follow-symbolic-links:
        description: "Indicates whether to follow symbolic links when resolving file paths"
        default: true
    ignores:
        description: |
            Files/directories to exclude from processing (comma/newline separated)
            Example: |
                src/theme/**/*.scss
                theme.css
                components/*.scss
    token:
        description: "GitHub token to use for pull requests creation"
        default: ${{ github.token }}
    target-branch:
        description: "Destination branch for automated changes (creates if missing)"
        default: "classname-updates"
    commit-message:
        description: "Commit message template"
        default: "chore: update Discord class names (automated)"
    pr-title:
        description: "Pull request title template"
        default: "Class Name Updates"
runs:
    using: "composite"
    steps:
        - name: Checkout Data
          uses: actions/checkout@v4
          with:
              repository: fedeericodl/discord-update-classnames
              ref: data
              path: $GITHUB_ACTION_PATH/data

        - name: Run Discord Update Class Names
          id: update-classnames
          shell: bash
          env:
              INPUT_FILES: ${{ inputs.files }}
              INPUT_FOLLOW_SYMBOLIC_LINKS: ${{ inputs.follow-symbolic-links }}
              INPUT_IGNORES: ${{ inputs.ignores }}
              INPUT_REPORT_OUTDATED: ${{ inputs.report-outdated }}
          run: |
              git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git config --global user.name "github-actions[bot]"

              node "$GITHUB_ACTION_PATH/dist/action/index.js"

        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v7
          with:
              token: ${{ inputs.token }}
              commit-message: ${{ inputs.commit-message }}
              branch: ${{ inputs.target-branch }}
              delete-branch: true
              title: ${{ inputs.pr-title }}
              body: |
                  Automated class name updates from Discord's latest changes

                  :warning: **Note:** This PR was automatically generated. Manual verification required before merging.

                  ---
                  Auto-generated by [discord-update-classnames][1]

                  [1]: https://github.com/fedeericodl/discord-update-classnames
branding:
    color: "gray-dark"
    icon: "code"
