name: "Discord Update Class Names"
author: "fedeericodl"
description: "Automated CSS class name synchronization tool for Discord theme developers"
inputs:
    files:
        description: |
            Files/directories to process (comma/newline separated)
            Example: |
                src/theme/**/*.scss
                theme.css
                components/*.scss
        required: true
    follow-symbolic-links:
        description: "Indicates whether to follow symbolic links when resolving file paths"
        default: true
    ignores:
        description: |
            Files/directories to exclude from processing (comma/newline separated)
            Example: |
                src/theme/**/*.scss
                theme.css
                components/*.scss
    token:
        description: "GitHub token to use for pull requests creation"
        default: ${{ github.token }}
    target-branch:
        description: "Destination branch for automated changes (creates if missing)"
        default: "classname-updates"
    commit-message:
        description: "Commit message template"
        default: "chore: update Discord class names (automated)"
    pr-title:
        description: "Pull request title template"
        default: "Class Name Updates"
outputs:
    version-hash:
        description: "Discord build version hash"
        value: ${{ steps.update-classnames.outputs.version-hash }}
    built-at:
        description: "Discord build date timestamp"
        value: ${{ steps.update-classnames.outputs.built-at }}
    formatted-built-at:
        description: "Formatted Discord build date"
        value: ${{ steps.update-classnames.outputs.formatted-built-at }}
    total-class-names:
        description: "Total class names found"
        value: ${{ steps.update-classnames.outputs.total-class-names }}
    changed-class-names:
        description: "Class names successfully updated"
        value: ${{ steps.update-classnames.outputs.changed-class-names }}
    failed-changed-class-names:
        description: "Class names that could not be updated"
        value: ${{ steps.update-classnames.outputs.failed-changed-class-names }}
runs:
    using: "composite"
    steps:
        - name: Checkout Data
          uses: actions/checkout@v4
          with:
              repository: fedeericodl/discord-update-classnames
              ref: data
              path: data

        - name: Run Discord Update Class Names
          id: update-classnames
          shell: bash
          env:
              INPUT_FILES: ${{ inputs.files }}
              INPUT_FOLLOW_SYMBOLIC_LINKS: ${{ inputs.follow-symbolic-links }}
              INPUT_IGNORES: ${{ inputs.ignores }}
          run: |
              git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git config --global user.name "github-actions[bot]"

              # HACK: Had to move data to the action path because GitHub doesn't like doing it in the checkout step
              mv "data" "$GITHUB_ACTION_PATH"
              node "$GITHUB_ACTION_PATH/dist/action/index.js"

        - name: Create Pull Request
          if: ${{ success() }}
          uses: peter-evans/create-pull-request@v7
          with:
              token: ${{ inputs.token }}
              commit-message: ${{ inputs.commit-message }}
              branch: ${{ inputs.target-branch }}
              delete-branch: true
              title: ${{ inputs.pr-title }}
              body: |
                  :warning: **Note:** This PR was automatically generated. Manual verification required before merging.

                  Updates to class names have been applied based on Discord build version `${{ steps.update-classnames.outputs.version-hash }}` (`${{ steps.update-classnames.outputs.formatted-built-at }}`).

                  **Changes**
                  - :sparkles: **${{ steps.update-classnames.outputs.changed-class-names }}** class names were successfully updated out of **${{ steps.update-classnames.outputs.total-class-names }}**.
                  - :x: **${{ steps.update-classnames.outputs.failed-changed-class-names }}** class names could not be updated:
                  ${{ steps.update-classnames.outputs.failed-changed-files }}

                  **Verification Checklist**
                  - [ ] Reviewed all changed files.
                  - [ ] Tested the theme on build version `${{ steps.update-classnames.outputs.version-hash }}`.

                  ---
                  Auto-generated by [discord-update-classnames])(https://github.com/fedeericodl/discord-update-classnames)
branding:
    color: "gray-dark"
    icon: "code"
