name: Fetch Data

on:
    schedule:
        - cron: "0 */1 * * *"
    workflow_dispatch:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    fetch:
        name: Fetch Data
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install
              uses: ./scripts/install

            - name: Run Fetch
              run: pnpm run start

            - name: Publish
              run: |
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "github-actions[bot]"

                  git add data
                  git diff-index --quiet HEAD || git commit -m "Automated update of class names"
                  git push origin main
