name: Fetch Data

on:
    schedule:
        - cron: "0 */1 * * *"
    workflow_dispatch:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    fetch:
        name: Fetch Data
        runs-on: ubuntu-latest
        env:
            DATA_PATH: ${{ github.workspace }}/data

        steps:
            - name: Checkout Script
              uses: actions/checkout@v4

            - name: Checkout Data
              uses: actions/checkout@v4
              with:
                  ref: "data"
                  path: ${{ env.DATA_PATH }}

            - name: Install
              uses: ./.github/actions/install

            - name: Run Fetch
              run: pnpm run start

            - name: Publish
              run: |
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "github-actions[bot]"

                  cd ${{ env.DATA_PATH }}
                  git add .
                  git diff-index --quiet HEAD || git commit -m "Automated update of class names"
                  git push origin data
